version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g wrangler
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npx nx run-many -t build
  post_build:
    commands:
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID} CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN} wrangler pages deploy ./dist/apps/customer --project-name=dashboard-develop --branch=main --commit-dirty=true
