/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StoreImport } from './routes/store'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const StoreStoreKeyProductsLazyImport = createFileRoute(
  '/store/$storeKey/products',
)()
const StoreStoreKeyOrdersLazyImport = createFileRoute(
  '/store/$storeKey/orders',
)()
const StoreStoreKeyDashboardLazyImport = createFileRoute(
  '/store/$storeKey/dashboard',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const StoreRoute = StoreImport.update({
  path: '/store',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const StoreStoreKeyProductsLazyRoute = StoreStoreKeyProductsLazyImport.update({
  path: '/$storeKey/products',
  getParentRoute: () => StoreRoute,
} as any).lazy(() =>
  import('./routes/store/$storeKey/products.lazy').then((d) => d.Route),
)

const StoreStoreKeyOrdersLazyRoute = StoreStoreKeyOrdersLazyImport.update({
  path: '/$storeKey/orders',
  getParentRoute: () => StoreRoute,
} as any).lazy(() =>
  import('./routes/store/$storeKey/orders.lazy').then((d) => d.Route),
)

const StoreStoreKeyDashboardLazyRoute = StoreStoreKeyDashboardLazyImport.update(
  {
    path: '/$storeKey/dashboard',
    getParentRoute: () => StoreRoute,
  } as any,
).lazy(() =>
  import('./routes/store/$storeKey/dashboard.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/store': {
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/store/$storeKey/dashboard': {
      preLoaderRoute: typeof StoreStoreKeyDashboardLazyImport
      parentRoute: typeof StoreImport
    }
    '/store/$storeKey/orders': {
      preLoaderRoute: typeof StoreStoreKeyOrdersLazyImport
      parentRoute: typeof StoreImport
    }
    '/store/$storeKey/products': {
      preLoaderRoute: typeof StoreStoreKeyProductsLazyImport
      parentRoute: typeof StoreImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  StoreRoute.addChildren([
    StoreStoreKeyDashboardLazyRoute,
    StoreStoreKeyOrdersLazyRoute,
    StoreStoreKeyProductsLazyRoute,
  ]),
  AboutLazyRoute,
])

/* prettier-ignore-end */
